name: API Tests (Playwright + Docker)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start FastAPI server using Docker
        run: docker compose -f ../docker-compose.yml up -d

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready..."
          for i in {1..15}; do
            if curl -sSf http://localhost:8000/health; then
              echo "API is healthy"
              break
            fi
            sleep 2
          done

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with HTML report
        run: npx playwright test --reporter=html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: api-tests/playwright-report
