name: API Tests (Playwright + Docker)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  playwright-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start API with Docker Compose
        run: docker compose -f ../docker-compose.yml up -d
        working-directory: api-tests

      - name: Wait for API to become healthy
        run: |
          echo "Waiting for API..."
          for i in {1..20}; do
            if curl -sSf http://localhost:8000/health; then
              echo "API is ready."
              break
            fi
            sleep 2
          done

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: api-tests/playwright-report/
