name: API Tests (Playwright + Docker)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    services:
      api:
        image: python:3.10-slim
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000/health || exit 1"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=5
        volumes:
          - ./bookstore:/app
        command: >
          bash -c "
            pip install -r /app/requirements.txt &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload
          "

    defaults:
      run:
        working-directory: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be healthy..."
          for i in {1..20}; do
            if curl -sSf http://localhost:8000/health; then
              echo "API is up!"
              break
            fi
            sleep 2
          done

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html --config=playwright.config.ts

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: api-tests/playwright-report
